version: '3.3'
services:

  minecraft:
    image: sidequest/mohist
    stdin_open: true
    tty: true
    ports:
      - 25575:25575
      - 25565:25565
      - 8123:8123
    volumes:
      - /opt/minecraft/config:/opt/minecraft/config
      - /opt/minecraft/worlds:/opt/minecraft/worlds
      - /opt/minecraft/plugins:/opt/minecraft/plugins
      - /opt/minecraft/mods:/opt/minecraft/mods
      - /opt/minecraft/ops.json:/opt/minecraft/ops.json
      - /opt/minecraft/banned-ips.json:/opt/minecraft/banned-ips.json
      - /opt/minecraft/banned-players.json:/opt/minecraft/banned-players.json
      - /opt/minecraft/whitelist.json:/opt/minecraft/whitelist.json

  express:
    image: sidequest/express
    ports:
      - "80:80"
