version: '3.3'
services:

  minecraft:
    image: webhippie/minecraft-forge:12.18.3
    ports:
      - 25575:25575
      - 25565:25565
      - 8123:8123
    volumes:
      - /var/lib/mc/minecraft:/var/lib/minecraft
      - /var/lib/mc/override:/etc/minecraft/override

