version: '3.3'
services:

  minecraft:
    image: sidequest/mohist
    stdin_open: true
    tty: true
    ports:
      - 25575:25575
      - 25565:25565
      - 8123:8123
    volumes:
      - /opt/minecraft/config:/opt/minecraft/config
      - /opt/minecraft/worlds:/opt/minecraft/worlds
      - /opt/minecraft/plugins:/opt/minecraft/plugins
      - /opt/minecraft/mods:/opt/minecraft/mods

