FROM ubuntu:20.04
LABEL maintainer="Shaluffob <shaluffob@sidequestvr.com>"
ARG MINECRAFT_VERSION=1.12.2
ARG MOHIST_VERSION=169
ARG MOHIST_DOWNLOAD_URL=https://ci.codemc.io/job/Mohist-Community/job/Mohist-${MINECRAFT_VERSION}/${MOHIST_VERSION}/artifact/projects/mohist/build/libs/mohist-${MINECRAFT_VERSION}-${MOHIST_VERSION}-server.jar
ARG JAVA_DOWNLOAD_URL=https://github.com/Shawiizz/shawiizz.github.io/releases/download/jrezipfiles/javalinux64.zip
ENV MINECRAFT_PATH=/opt/minecraft
WORKDIR ${MINECRAFT_PATH}
RUN apt-get update
RUN apt-get install unzip python curl -y
RUN curl -L ${MOHIST_DOWNLOAD_URL} --output mohist.jar
RUN curl -L ${JAVA_DOWNLOAD_URL} --output java.zip
RUN echo "eula=true" > eula.txt
RUN unzip java.zip -d ./java/
RUN chmod +x ./java/bin/java
ENV JAVA_PATH=${MINECRAFT_PATH}/java/bin/java
#RUN ./bin/java -jar ${MINECRAFT_BUILD_PATH}/mohist.jar; exit 0
ENV PROPERTIES_LOCATION=${CONFIG_PATH}/server.properties
ENV JAVA_HEAP_SIZE=54G
ENV JAVA_ARGS="-server"
ENV SPIGOT_ARGS="--nojline"
ENV PAPER_ARGS=""
ENV CONFIG_PATH=${MINECRAFT_PATH}/config
ENV PLUGINS_PATH=${MINECRAFT_PATH}/plugins
ENV MODS_PATH=${MINECRAFT_PATH}/mods
ENV WORLDS_PATH=${MINECRAFT_PATH}/worlds
ENV PROPERTIES_LOCATION=${CONFIG_PATH}/server.properties
RUN mkdir ${CONFIG_PATH} ${PLUGINS_PATH} ${WORLDS_PATH} && \
    chmod 777 ${CONFIG_PATH} ${PLUGINS_PATH} ${WORLDS_PATH}
ADD https://bootstrap.pypa.io/get-pip.py .
RUN python get-pip.py --user
RUN /root/.local/bin/pip install mcstatus
#HEALTHCHECK --interval=10s --timeout=5s --start-period=120s \
#    CMD mcstatus localhost:$( cat $PROPERTIES_LOCATION | grep "server-port" | cut -d'=' -f2 ) ping
EXPOSE 25565 25575 8123
CMD ${JAVA_PATH} -jar $JAVA_ARGS \
    -Xmx$JAVA_HEAP_SIZE -Xms$JAVA_HEAP_SIZE \
    $MINECRAFT_PATH/mohist.jar \
    $SPIGOT_ARGS \
    --bukkit-settings $CONFIG_PATH/bukkit.yml \
    --plugins $PLUGINS_PATH \
    --world-dir $WORLDS_PATH \
    --spigot-settings $CONFIG_PATH/spigot.yml \
    --commands-settings $CONFIG_PATH/commands.yml \
    --config $PROPERTIES_LOCATION \
    --paper-settings $CONFIG_PATH/paper.yml \
    $PAPERSPIGOT_ARGS
#ENTRYPOINT ["tail", "-f", "/dev/null"]
