FROM node:14
WORKDIR /usr/src/app
COPY . .
RUN apt-get -y update
RUN apt-get -y install jq
RUN yarn
RUN yarn global add forever
EXPOSE 80
CMD cd /usr/src/app/ && forever -c "./node_modules/.bin/ts-node" index.ts

